### ISSUE TITLE
JSON KeyError

### ISSUE THREAD

**Issue by hungys** [hungys/RamboBoxGen#7]
How to reproduce:

```
$ python3 box.py 0041600233
```

Result:

```
Traceback (most recent call last):
  File "box.py", line 456, in <module>
    print_team_box(box_json, home=False)
  File "box.py", line 423, in print_team_box
    print_header_team(box, home)
  File "box.py", line 86, in print_header_team
    line += (" (" + box["stats"]["visitor"]["vr"] + ")")
KeyError: 'vr'
```

Currently we didn't have error handling for dictionary object, but maybe the returned schema is not always perfect...?

**Comment by hungys** [comment]
Fixed in https://github.com/hungys/RamboBoxGen/commit/c4524499dc2ae34b111e9209994657d048c09c81
